export type IndianLocation = { state: string; city: string };

// State / UT -> capital (used as the default "browse by state" city)
export const INDIAN_STATES: IndianLocation[] = [
  { state: "Andhra Pradesh", city: "Amaravati" },
  { state: "Arunachal Pradesh", city: "Itanagar" },
  { state: "Assam", city: "Dispur" },
  { state: "Bihar", city: "Patna" },
  { state: "Chhattisgarh", city: "Raipur" },
  { state: "Goa", city: "Panaji" },
  { state: "Gujarat", city: "Gandhinagar" },
  { state: "Haryana", city: "Chandigarh" },
  { state: "Himachal Pradesh", city: "Shimla" },
  { state: "Jharkhand", city: "Ranchi" },
  { state: "Karnataka", city: "Bengaluru" },
  { state: "Kerala", city: "Thiruvananthapuram" },
  { state: "Madhya Pradesh", city: "Bhopal" },
  { state: "Maharashtra", city: "Mumbai" },
  { state: "Manipur", city: "Imphal" },
  { state: "Meghalaya", city: "Shillong" },
  { state: "Mizoram", city: "Aizawl" },
  { state: "Nagaland", city: "Kohima" },
  { state: "Odisha", city: "Bhubaneswar" },
  { state: "Punjab", city: "Chandigarh" },
  { state: "Rajasthan", city: "Jaipur" },
  { state: "Sikkim", city: "Gangtok" },
  { state: "Tamil Nadu", city: "Chennai" },
  { state: "Telangana", city: "Hyderabad" },
  { state: "Tripura", city: "Agartala" },
  { state: "Uttar Pradesh", city: "Lucknow" },
  { state: "Uttarakhand", city: "Dehradun" },
  { state: "West Bengal", city: "Kolkata" },
  { state: "Delhi", city: "New Delhi" },
  { state: "Jammu & Kashmir", city: "Srinagar" },
  { state: "Ladakh", city: "Leh" },
  { state: "Puducherry", city: "Puducherry" },
  { state: "Andaman & Nicobar", city: "Port Blair" },
  { state: "Chandigarh", city: "Chandigarh" },
  { state: "Dadra & Nagar Haveli", city: "Silvassa" },
  { state: "Lakshadweep", city: "Kavaratti" },
];

// Major Indian cities grouped by state / UT for the browse-by-city view.
export const INDIAN_CITIES_BY_STATE: Record<string, string[]> = {
  "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Tirupati", "Rajahmundry", "Kakinada", "Anantapur", "Kadapa", "Amaravati", "Eluru", "Ongole", "Chittoor"],
  "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro", "Bomdila", "Tezu"],
  "Assam": ["Guwahati", "Dispur", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tinsukia", "Tezpur", "Bongaigaon", "Karimganj"],
  "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga", "Bihar Sharif", "Purnia", "Arrah", "Begusarai", "Katihar", "Munger", "Chhapra"],
  "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg", "Rajnandgaon", "Jagdalpur", "Ambikapur", "Raigarh"],
  "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
  "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar", "Junagadh", "Anand", "Bharuch", "Mehsana", "Porbandar", "Navsari"],
  "Haryana": ["Faridabad", "Gurugram", "Panipat", "Ambala", "Yamunanagar", "Rohtak", "Hisar", "Karnal", "Sonipat", "Panchkula", "Bhiwani", "Sirsa"],
  "Himachal Pradesh": ["Shimla", "Manali", "Dharamshala", "Solan", "Mandi", "Kullu", "Hamirpur", "Bilaspur", "Una", "Chamba", "Palampur"],
  "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh", "Deoghar", "Giridih", "Ramgarh", "Phusro"],
  "Karnataka": ["Bengaluru", "Mysuru", "Mangaluru", "Hubli", "Belgaum", "Davangere", "Ballari", "Tumakuru", "Shivamogga", "Udupi", "Hassan", "Bidar", "Raichur", "Vijayapura"],
  "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Alappuzha", "Kannur", "Palakkad", "Malappuram", "Kottayam", "Pathanamthitta", "Idukki"],
  "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Dewas", "Satna", "Ratlam", "Rewa", "Khandwa", "Burhanpur"],
  "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Solapur", "Thane", "Navi Mumbai", "Kolhapur", "Amravati", "Akola", "Sangli", "Jalgaon", "Latur", "Nanded", "Satara", "Ratnagiri"],
  "Manipur": ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Ukhrul"],
  "Meghalaya": ["Shillong", "Tura", "Jowai", "Nongstoin", "Williamnagar"],
  "Mizoram": ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib"],
  "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha", "Mon"],
  "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri", "Balasore", "Bhadrak", "Baripada", "Jharsuguda"],
  "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Hoshiarpur", "Pathankot", "Moga", "Firozpur"],
  "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner", "Ajmer", "Alwar", "Bhilwara", "Sikar", "Pali", "Sri Ganganagar", "Tonk", "Mount Abu", "Pushkar"],
  "Sikkim": ["Gangtok", "Namchi", "Mangan", "Gyalshing", "Pelling"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Tiruppur", "Erode", "Vellore", "Thoothukudi", "Dindigul", "Thanjavur", "Kanchipuram", "Ooty", "Kanyakumari"],
  "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam", "Mahbubnagar", "Ramagundam", "Secunderabad", "Nalgonda"],
  "Tripura": ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar", "Ambassa", "Belonia"],
  "Uttar Pradesh": ["Lucknow", "Kanpur", "Agra", "Varanasi", "Prayagraj", "Ghaziabad", "Noida", "Meerut", "Bareilly", "Aligarh", "Moradabad", "Saharanpur", "Gorakhpur", "Firozabad", "Jhansi", "Mathura", "Ayodhya", "Mirzapur"],
  "Uttarakhand": ["Dehradun", "Haridwar", "Rishikesh", "Nainital", "Roorkee", "Haldwani", "Rudrapur", "Mussoorie", "Almora", "Pithoragarh"],
  "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Darjeeling", "Bardhaman", "Malda", "Kharagpur", "Haldia", "Jalpaiguri", "Cooch Behar"],
  "Delhi": ["New Delhi", "Delhi", "Dwarka", "Rohini", "Saket", "Pitampura", "Karol Bagh"],
  "Jammu & Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Sopore", "Udhampur", "Kathua", "Pulwama"],
  "Ladakh": ["Leh", "Kargil", "Nubra", "Diskit"],
  "Puducherry": ["Puducherry", "Karaikal", "Yanam", "Mahe"],
  "Andaman & Nicobar": ["Port Blair", "Diglipur", "Mayabunder", "Car Nicobar"],
  "Chandigarh": ["Chandigarh"],
  "Dadra & Nagar Haveli": ["Silvassa", "Daman", "Diu"],
  "Lakshadweep": ["Kavaratti", "Agatti", "Minicoy", "Amini"],
};
